In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv(r'fares.csv')

In [3]:
dataset.head()

vendor_id payment_type  fare_amount  surcharge  mta_tax  tip_amount  \
0       VTS          CRD          8.0        0.0      0.5         2.5   
1       VTS          CSH         18.0        0.5      0.5         0.0   
2       VTS          CRD          3.5        0.0      0.5         0.7   
3       VTS          CRD         11.5        0.0      0.5         2.3   
4       VTS          CSH          6.5        0.0      0.5         0.0   

   tolls_amount  total_amount  
0           0.0          11.0  
1           0.0          19.0  
2           0.0           4.7  
3           0.0          14.3  
4           0.0           7.0

In [4]:
dataset.isnull().any()

vendor_id       False
payment_type    False
fare_amount     False
surcharge       False
mta_tax         False
tip_amount      False
tolls_amount    False
total_amount    False
dtype: bool

In [6]:
X

array([['VTS', 'CRD', 8.0, ..., 0.5, 2.5, 0.0],
       ['VTS', 'CSH', 18.0, ..., 0.5, 0.0, 0.0],
       ['VTS', 'CRD', 3.5, ..., 0.5, 0.7, 0.0],
       ...,
       ['VTS', 'CSH', 7.5, ..., 0.5, 0.0, 0.0],
       ['VTS', 'CSH', 14.0, ..., 0.5, 0.0, 0.0],
       ['VTS', 'CRD', 6.5, ..., 0.5, 1.0, 0.0]], dtype=object)

In [7]:
y=dataset.iloc[:,7].values

In [8]:
y

array([11. , 19. ,  4.7, ...,  8. , 15.5,  9. ])

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
lb=LabelEncoder()

In [11]:
X[:,0]=lb.fit_transform(X[:,0])

In [12]:
X[:,1]=lb.fit_transform(X[:,1])

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
oh1=OneHotEncoder(categorical_features=[1])

In [15]:
x=oh1.fit_transform(X).toarray()
x

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[1. , 0. , 0. , ..., 0.5, 2.5, 0. ],
       [0. , 1. , 0. , ..., 0.5, 0. , 0. ],
       [1. , 0. , 0. , ..., 0.5, 0.7, 0. ],
       ...,
       [0. , 1. , 0. , ..., 0.5, 0. , 0. ],
       [0. , 1. , 0. , ..., 0.5, 0. , 0. ],
       [1. , 0. , 0. , ..., 0.5, 1. , 0. ]])

In [16]:
x=x[:,1:]
x

array([[0. , 0. , 0. , ..., 0.5, 2.5, 0. ],
       [1. , 0. , 0. , ..., 0.5, 0. , 0. ],
       [0. , 0. , 0. , ..., 0.5, 0.7, 0. ],
       ...,
       [1. , 0. , 0. , ..., 0.5, 0. , 0. ],
       [1. , 0. , 0. , ..., 0.5, 0. , 0. ],
       [0. , 0. , 0. , ..., 0.5, 1. , 0. ]])

In [17]:
dataset.head()

vendor_id payment_type  fare_amount  surcharge  mta_tax  tip_amount  \
0       VTS          CRD          8.0        0.0      0.5         2.5   
1       VTS          CSH         18.0        0.5      0.5         0.0   
2       VTS          CRD          3.5        0.0      0.5         0.7   
3       VTS          CRD         11.5        0.0      0.5         2.3   
4       VTS          CSH          6.5        0.0      0.5         0.0   

   tolls_amount  total_amount  
0           0.0          11.0  
1           0.0          19.0  
2           0.0           4.7  
3           0.0          14.3  
4           0.0           7.0

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [19]:
x_train

array([[0.  , 0.  , 0.  , ..., 0.5 , 2.75, 0.  ],
       [1.  , 0.  , 0.  , ..., 0.5 , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.5 , 4.77, 5.33],
       ...,
       [1.  , 0.  , 0.  , ..., 0.5 , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.5 , 2.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.5 , 5.3 , 4.8 ]])

In [20]:
x_test

array([[1. , 0. , 0. , ..., 0.5, 0. , 0. ],
       [0. , 0. , 0. , ..., 0.5, 1.5, 0. ],
       [1. , 0. , 0. , ..., 0.5, 0. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 0.5, 1. , 0. ],
       [0. , 0. , 0. , ..., 0.5, 7.4, 0. ],
       [0. , 0. , 0. , ..., 0.5, 2.5, 0. ]])

In [21]:
y_train

array([14.25,  6.  , 29.1 , ...,  8.  , 24.  , 37.1 ])

In [22]:
y_test

array([ 7. ,  9. ,  5. , ...,  8. , 44.4, 11. ])

In [23]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [24]:
from sklearn.tree import DecisionTreeRegressor

In [25]:
dt=DecisionTreeRegressor()

In [26]:
dt.fit(x_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [27]:
y_pred=dt.predict(x_test)

In [28]:
y_pred=dt.predict([[0,0,0,0,0,8.0,0,1.0,0.25,3]])

In [29]:
y_pred

array([132.33])